In [22]:
from timeit import timeit
n = 100000

In [48]:
def squares2():
    array = [i**2 for i in range(n+1)]

In [26]:
timeit(arraycreator, number=100)

4.686073739955532

In [27]:
"""
numpy - numerical python
"""
import numpy as np

In [29]:
np.sin(0.25 * np.pi)**2 == 0.5

False

In [32]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [37]:
arr2 = np.array([0, 1/2, 2], dtype=float)
arr2

array([0. , 0.5, 2. ])

In [38]:
arr1.dtype

dtype('int32')

In [39]:
arr2.dtype

dtype('float64')

In [42]:
np.sin(arr2* np.pi)**2.round(2)

SyntaxError: invalid syntax (<ipython-input-42-a88a5228d057>, line 1)

In [43]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [46]:
def squares3():
    return np.arange(1,n+1,)**2

In [49]:
timeit(squares2, number = 100) / timeit(squares3, number = 100)

322.84325899609274

In [51]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [53]:
A = np.matrix([[1,2],[3,4]])
I = np.eye(len(A))

In [54]:
A*I

matrix([[1., 2.],
        [3., 4.]])

In [55]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.zeros((2,2,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [57]:
np.random.rand(2, 5)

array([[0.83687913, 0.37354657, 0.13583473, 0.20274504, 0.63085346],
       [0.29351755, 0.25275529, 0.93471906, 0.71864786, 0.28234769]])

In [59]:
arr = 100 * np.random.rand(10,10)

In [60]:
arr[:, 0]

array([81.20629961, 24.21876002, 29.82025809, 43.37970735, 91.08211963,
        2.64743795, 94.75392036, 79.57898394, 46.26545154, 73.26419659])

In [61]:
arr[0,:]

array([81.20629961, 29.77050471, 40.06449441, 18.46356382, 28.49051444,
       17.97432797, 31.19813529, 38.53628194,  9.22035278, 93.38167493])

In [63]:
arr[:,::4]

array([[81.20629961, 28.49051444,  9.22035278],
       [24.21876002,  1.97190009, 85.38495234],
       [29.82025809, 70.74611928, 59.44401745],
       [43.37970735,  0.62146248, 40.77460261],
       [91.08211963, 37.89508395, 26.0667181 ],
       [ 2.64743795, 63.47924102, 41.27085678],
       [94.75392036, 14.82789604,  6.68773406],
       [79.57898394, 78.75020119, 39.83806365],
       [46.26545154, 70.71187968, 58.11678475],
       [73.26419659, 82.12431843, 56.44909559]])

In [65]:
arr[:, (0, 4, 8)] < 50

array([[False,  True,  True],
       [ True,  True, False],
       [ True, False, False],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True],
       [False, False,  True],
       [ True, False, False],
       [False, False, False]])

In [66]:
arr[arr<50]

array([29.77050471, 40.06449441, 18.46356382, 28.49051444, 17.97432797,
       31.19813529, 38.53628194,  9.22035278, 24.21876002,  6.59056796,
        1.97190009, 23.26867774, 29.82025809,  3.61478069, 14.51173312,
        9.35471313, 43.37970735,  8.71164129,  0.62146248, 34.74008566,
       41.84580943, 36.77194714, 40.77460261, 35.37464447, 37.89508395,
       40.39204901, 30.03659348, 31.80785361, 26.0667181 ,  2.37656357,
        2.64743795,  6.46952104, 32.64179295, 24.06157984, 41.27085678,
        3.71923458,  2.0565824 , 14.82789604, 12.5333356 , 37.08639019,
        6.68773406,  8.25409322, 28.48165077, 10.98486001, 39.83806365,
       35.95445844, 46.26545154, 12.72878708, 43.69872233,  2.69813873,
       29.30980723, 39.86883346, 16.5920892 , 41.88608953])

In [67]:
arr[arr<50] = 0
arr

array([[81.20629961,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , 93.38167493],
       [ 0.        ,  0.        , 77.15956205, 78.92069286,  0.        ,
        51.17737169,  0.        , 75.34286163, 85.38495234, 54.10951772],
       [ 0.        , 58.97744434, 52.23434052, 92.51269201, 70.74611928,
         0.        ,  0.        ,  0.        , 59.44401745, 59.270242  ],
       [ 0.        , 83.63931421, 56.38734298,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , 63.30901834],
       [91.08211963, 68.34802088, 91.66149388,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , 51.06310555,  0.        ,  0.        , 63.47924102,
         0.        , 54.73267899, 77.9343266 ,  0.        , 84.91218843],
       [94.75392036, 87.2828837 ,  0.        ,  0.        ,  0.        ,
         0.        , 86.53717128,  0.        

In [69]:
np.arctan(arr) / np.pi

array([[0.49608043, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49659143],
       [0.        , 0.        , 0.49587489, 0.49596693, 0.        ,
        0.49378105, 0.        , 0.49577543, 0.49627223, 0.49411797],
       [0.        , 0.49460337, 0.49390686, 0.49655942, 0.49550097,
        0.        , 0.        , 0.        , 0.49464572, 0.49463003],
       [0.        , 0.49619444, 0.49435553, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.49497254],
       [0.49650538, 0.49534314, 0.49652747, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.49376714, 0.        , 0.        , 0.49498602,
        0.        , 0.49418493, 0.49591589, 0.        , 0.49625148],
       [0.49664079, 0.49635328, 0.        , 0.        , 0.        ,
        0.        , 0.49632186, 0.        , 0.        , 0.49646446],
       [0.49600029, 0.49490772, 0.4961517

In [72]:
A = arr[:5,:5]
np.linalg.det(A)

1728613008.919631

In [74]:
B = np.random.rand(5)
x = np.linalg.solve(A,B)

In [75]:
x

array([ 0.00195526, -0.0005666 ,  0.00613287, -0.00542167,  0.01665663])